---

- hosts: "{{ host }}"
  become: yes
  gather_facts: no

  pre_tasks:
    - name: "Install python2"
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  roles:
    - management
    - deploy